/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.access;

import java.awt.Color;

/**
 *
 * @author Administrator
 */
public class panelBantuan extends javax.swing.JPanel {

    /**
     * Creates new form panelBantuan
     */
    public panelBantuan() {
        initComponents();
        setOpaque(false);
        
        jTextPane1.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTextPane1.setText("Anda bisa mendapatkan dukungan secara penuh melalui online maupun Offline, dengan mengirim pesan kepada tim kami melalui e-mail.\n\nDengan subjek “We Need Help”. Kami akan merespon Anda dengan cepat.\n\nEmail : teambullseyev@gmail.com\n\nAtau anda juga dapat menghubungi kami melalui WhatsApp\n");
        jTextPane1.setOpaque(false);
        add(jTextPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 710, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/what.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 45)); // NOI18N
        jLabel2.setText("Layanan Bantuan ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
